# Generated by Django 3.1 on 2020-08-06 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20200806_1006'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpost',
            old_name='user',
            new_name='uploader',
        ),
    ]
