# Generated by Django 3.1 on 2020-08-12 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_userpost_likes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostLike',
        ),
    ]
